// <auto-generated />
using Adv.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Adv.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211020192308_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Adv.API.Model.Acao", b =>
                {
                    b.Property<int>("AcaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor");

                    b.Property<string>("Causa");

                    b.Property<string>("DataEntrada");

                    b.Property<string>("Reu");

                    b.Property<string>("Testemunha");

                    b.Property<int>("ValorInicial");

                    b.HasKey("AcaoId");

                    b.ToTable("Acao");
                });
#pragma warning restore 612, 618
        }
    }
}
